# LamdaTest configuration tool: https://www.lambdatest.com/capabilities-generator/
breakpoint: 'desktop'
caps:
  browserName: 'chrome'
  version: '64.0'
  platform: 'Windows 10'
  resolution: '1440x900'