<%
  config_requires = "--require config/setup.rb"
  full_execution = "--require config/options/full_execution.rb"
  browserstack = "FYT_DRIVER=browserstack"
  saucelabs = "FYT_DRIVER=saucelabs"
  pretty_format = "-f pretty"
  debug = "--tags '@debug'"
  not_debug = "--tags 'not @debug'"
  env_prod = "FYT_ENVIRONMENT=prod"
%>
default: <%= config_requires %> <%= full_execution %> <%= pretty_format %> <%= not_debug %>
fast: <%= config_requires %> <%= pretty_format %> <%= not_debug %>
prod: <%= config_requires %> <%= env_prod %> <%= pretty_format %> <%= not_debug %>
browserstack: <%= browserstack %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
saucelabs: <%= saucelabs %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
debug: <%= config_requires %> <%= pretty_format %> <%= debug %>