<%
  config_requires = "--require config/setup.rb"
  full_execution = "--require config/options/full_execution.rb"
  browserstack = "FYT_DRIVER=browserstack"
  saucelabs = "FYT_DRIVER=saucelabs"
  lamdatest = "FYT_DRIVER=lamdatest"
  local = "FYT_DRIVER=local"
  pretty_format = "-f pretty"
  debug = "--tags '@debug'"
  not_debug = "--tags 'not @debug'"
  env_prod = "FYT_ENVIRONMENT=prod"
  mobile = "--tags 'not @desktop' FYT_MOBILE=true"
  desktop = "--tags 'not @mobile' FYT_MOBILE=false"
%>
default: <%= local %> <%= config_requires %> <%= desktop %> <%= full_execution %> <%= pretty_format %> <%= not_debug %>
fast: <%= local %> <%= config_requires %> <%= desktop %> <%= pretty_format %> <%= not_debug %>
prod: <%= local %> <%= config_requires %> <%= desktop %> <%= env_prod %> <%= pretty_format %> <%= not_debug %>
browserstack: <%= browserstack %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
saucelabs: <%= saucelabs %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
lamdatest: <%= lamdatest %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
mobile: <%= local %> <%= config_requires %> <%= mobile %> <%= pretty_format %> <%= not_debug %>
debug: <%= local %> <%= config_requires %> <%= desktop %> <%= pretty_format %> <%= debug %>
