<%
  config_requires = "--require config/setup.rb"
  full_execution = "--require config/options/full_execution.rb"
  browserstack = "FYT_DRIVER=browserstack"
  saucelabs = "FYT_DRIVER=saucelabs"
  lamdatest = "FYT_DRIVER=lamdatest"
  local = "FYT_DRIVER=local"
  appium = "FYT_DRIVER=appium"
  pretty_format = "-f pretty"
  debug = "--tags '@debug'"
  not_debug = "--tags 'not @debug'"
  env_prod = "FYT_ENVIRONMENT=prod"
  mobile = "--tags 'not @desktop' LOCAL_CONFIG_NAME=iphone_x"
  desktop = "--tags 'not @mobile'"
%>
default: <%= local %> <%= config_requires %> <%= desktop %> <%= full_execution %> <%= pretty_format %> <%= not_debug %>
fast: <%= local %> <%= config_requires %> <%= desktop %> <%= pretty_format %> <%= not_debug %>
prod: <%= local %> <%= config_requires %> <%= desktop %> <%= env_prod %> <%= pretty_format %> <%= not_debug %>
browserstack: <%= browserstack %> <%= env_prod %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
saucelabs: <%= saucelabs %> <%= env_prod %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
lamdatest: <%= lamdatest %> <%= env_prod %> <%= desktop %> <%= config_requires %>  <%= pretty_format %> <%= not_debug %>
mobile: <%= local %> <%= config_requires %> <%= mobile %> <%= pretty_format %> <%= not_debug %>
appium: <%= appium %> <%= config_requires %> <%= mobile %> <%= pretty_format %> <%= not_debug %>
debug: <%= local %> <%= config_requires %> <%= desktop %> <%= pretty_format %> <%= debug %>
