# BrowserStack Capabilities Generator Tool: https://www.browserstack.com/automate/capabilities
breakpoint: 'mobile'
caps:
  os_version: '12'
  device: 'iPhone XS'
  real_mobile: true
  browserstack.local: 'false'
