# BrowserStack Capabilities Generator Tool: https://www.browserstack.com/automate/capabilities
caps:
  os: 'OS X'
  os_version: 'Mojave'
  resolution: '1600x1200'
  browser: 'Safari'
  browser_version: '12.0'
  browserstack.local: 'false'
