# BrowserStack Capabilities Generator Tool: https://www.browserstack.com/automate/capabilities
caps:
  os: 'Windows'
  os_version: '7'
  resolution: '1440x900'
  browser: 'Firefox'
  browser_version: '66.0'
  browserstack.local: 'false'

