# BrowserStack Capabilities Generator Tool: https://www.browserstack.com/automate/capabilities
caps:
  os: 'Windows'
  os_version: '10'
  resolution: '1440x900'
  browser: 'Chrome'
  browser_version: '73.0'
  browserstack.local: 'false'
