# BrowserStack Capabilities Generator Tool: https://www.browserstack.com/automate/capabilities
breakpoint: 'desktop'
caps:
  os: 'Windows'
  os_version: '10'
  resolution: '1440x900'
  browser: 'Edge'
  browser_version: '18.0'
  browserstack.local: 'false'
