# Chrome Dev Tools, see: https://developers.google.com/web/tools/chrome-devtools/device-mode/
breakpoint: 'desktop'
caps:
  chromeOptions:
    mobileEmulation:
      deviceMetrics:
        width: 1194
        height: 834
        pixelRatio: 2.0
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/16A5288q Safari/605.1.15'